const SOLANA_DERIVATION_PATH = "m/44'/501'/";
const ETHEREUM_DERIVATION_PATH = "m/44'/60'/";
const BITCOIN_DERIVATION_PATH = "m/44'/0'/";

export {
  SOLANA_DERIVATION_PATH,
  ETHEREUM_DERIVATION_PATH,
  BITCOIN_DERIVATION_PATH,
};
